[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vote_dapp = "3Qs3YBv9mw656z56RKSJa2MLznZKrpiRgvME33TopxYi"

[programs.devnet]
vote_dapp = "3Qs3YBv9mw656z56RKSJa2MLznZKrpiRgvME33TopxYi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
